version: '3'
services:
  app-db:
    #image: docker-registry.dglecom.net/percona:5.6
    image: percona:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stockdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "33306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql